---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${BASE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |
      #!/bin/bash
      echo "Hello"
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |
      #!/bin/bash
      echo "Hello"
