---
stages:
- name: Artifact Build
  inputs:
  - type: git
    branch: master
    service: ${BASE_GIT_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build Artifact
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      export JAVA_HOME=$JAVA8_HOME
      chmod +x gradlew
      ./gradlew build
