---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${BASE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |
      #!/bin/bash
      echo "Building"
      export JAVA_HOME=$JAVA8_HOME
      chmod +x gradlew
      ./gradlew build
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |
      #!/bin/bash
      echo "Deploying"
      ls
      echo "DOne deploying"
